### ISSUE TITLE
Turn bug (overflow?)

### ISSUE THREAD

**Issue by kohanov** [CT-18/cg_common#14]
Для красной точки на примере ниже поворот посчитан с неправильным знаком
![image](https://cloud.githubusercontent.com/assets/15210688/23566804/84f737b8-0064-11e7-80f3-8f122df20de8.png)

**Comment by artemZholus** [comment]
вот ситуация на x64
![screenshot from 2017-03-07 02-26-46](https://cloud.githubusercontent.com/assets/11904422/23634878/bf44d198-02dd-11e7-9245-8726a9c73507.png)
Вывод: ставим х64

**Comment by artemZholus** [comment]
но зафорсить np.int64 - норм идея, сейчас 2к17, как-никак.
