### ISSUE TITLE
12_sum_minkowski

### ISSUE THREAD

**Issue by CawaEast** [CT-18/cg_common#4]
класс точки/вектор:
 - математические операции вида сложение, вычитание, различные умножения
 - доступ к полям координат
класс многоугольник:
 - возможность проитерироваться по вершинам многоугольника в порядке против часовой стрелки(следующая вершина - смежная по ребру против часовой стрелки) / метод, возвращающий следующую вершину (аргумент - текущая вершина)
 - доступ к вершинам
 - (не обязательно) метод возвращающий самую нижнюю (среди них левую) вершину
 - создание многоугольника из набора точек / добавление к многоугольнику вершины (если будет класс именно выпуклого многоугольника)

**Comment by artemZholus** [comment]
чем отличается "класс многоугольник" от "класс множество точек + инвариант"?

**Comment by artemZholus** [comment]
лучше использовать второй вариант, так как он гибче.
в нем будет метод .map (или как-то по-другому будет называться), предпоследний сводится к вызову argmax от .map

**Comment by artemZholus** [comment]
Класс многоугольника готов (на самом деле, там класс PointSet, в общем см. мой первый коммент)

**Comment by artemZholus** [comment]
есть несколько способов, вот два самых простых 
как получить координату с наибольшим y (например):
    
    # инициализация
    set = PointSet(2)
    set.append(Point(0, 0))
    set.append(Point(1, 0))
    set.append(Point(0, 1))
    # способ 1
    set.max() # лексикографический максимум - самая "правая верхняя" точка
    # способ 2
    set.maximize(operator.itemgetter(1)) # максимум по 2й координате
