### ISSUE TITLE
22_segment_intersect

### ISSUE THREAD

**Issue by akustareva** [CT-18/cg_common#7]
класс точки с операциями
* сложения
* вычитания
* меньше (больше) (сравнение в лексикографическом порядке: меньше тот, у которого `x` меньше, при равенстве `x` аналогично для `y`)
* равно

класс отрезка с полями `a`, `b` и `id`, свойством, что точка `a` меньше `b`, и операциями
* меньше (больше) (сравнение в лексикографическом порядке: меньше тот, у кого `a` меньше, при равенстве `a` сравниваем `b`)
* равно
* строковое представление 

класс "тип события" (enum) с полями
* левый конец отрезка
* правый конец отрезка
* пересечение отрезков

класс событие (`event`) с полями `segment`, `type`, `addit_segment`, `inter_point` - описывает события концов/пересечений отрезков, и в случае события "пересечение" хранит точку пересечения и второй отрезок. Операции:
* сравнения меньше (больше) и равно - сравнение фильтрованным вычислением предикатов.

**Comment by artemZholus** [comment]
класс точки с этими операциями уже есть

**Comment by akustareva** [comment]
Хорошо. Класс `event` (и, соответственно, тип события) не нужно добавлять в библиотеку. Я единственный использующий его конспект. Лучше сделаю упражнение на нетривиальное сравнение событий.

**Comment by artemZholus** [comment]
ой
