### ISSUE TITLE
2_rect_intersect

### ISSUE THREAD

**Issue by Kurkin** [CT-18/cg_common#9]
- Структуру для хранения части пространства, то есть для плоскости какой-нибудь box(left, ceil, right, floor) и методы проверяющие принадлежит ли точка области, пересекаются ли 2 области, лежит ли одна область внутри другой.

- Генератор рандомных точек

**Comment by artemZholus** [comment]
генератор готов.

**Comment by Kurkin** [comment]
-  Конструктор PointSet от генератора
- Возможность брать слайс от PointSet, т.е. что-то типа: PointSet[index:]

Возможно, вместо отельного класса box, в pointSet стоит добавить прямоугольник в котором лежат точки. Тогда было бы круто уметь делать split pointSet'a, например: плоскость разбивать прямой и получать 2 pointSet'а, соответсвующие полуплоскости слева и справа от прямой.

**Comment by artemZholus** [comment]
задача про box слишком специализированная, поэтому скорее всего, ее не будет.
